[package]
name = "bevy-earcutr"
version = "0.2.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2018"
description = "earcutr + Bevy"
license = "MIT/Apache-2.0"
repository = "https://github.com/frewsxcv/bevy-earcutr"

[dependencies]
bevy_render = "0.5"
earcutr = "0.1"
