[package]
name = "bevy-earcutr"
version = "0.3.1"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2018"
description = "earcutr + Bevy"
license = "MIT/Apache-2.0"
repository = "https://github.com/frewsxcv/bevy-earcutr"
resolver = "2"

[dependencies]
bevy_render = "0.6"
earcutr = "0.2"
